export const CONSTANTS = {
  WORKOUT: {
    UI: {
      ACTIONS: {
        EDIT_WORKOUT: "Edit workout",
        DELETE_WORKOUT: "Delete workout",
        EXPORT: "📸 Export",
      },
      LABELS: {
        EXERCISES_COUNT: "3 exercises",
        WORKOUT_PROGRESS: "Workout progress",
        TRAINING_ANALYSIS: "Training analysis",
        FRONT: "Front",
        BACK: "Back",
        MUSCLE_HEAT_MAP: "Muscle heat map",
        TOTAL_WORKOUT: "Total workout",
        WORKOUT_DATA: "Workout data",
        WORKOUT_LOG: "Workout log",
        CURRENT_FILE: "Current file",
        DASHBOARD: "Dashboard",
      },
      DISPLAY: {
        PERCENTAGE_45: "45%",
      },
      BUTTONS: {
        CREATE_FILE: "Create file",
      },
    },
    MESSAGES: {
      NO_DATA: "No workout data available",
      LOADING: "Loading workout data...",
      NO_DATA_PERIOD: "No workout data found for the selected time period.",
      TIMER_COMPLETED: "Timer completed!",
      WARNINGS: {
        IMBALANCE_ALERTS: "⚠️ Imbalance alerts",
      },
      SUCCESS: {
        NO_IMBALANCES: "✅ No major muscle imbalances detected",
        CSV_CREATED: "CSV log file created successfully!",
        CODE_INSERTED: "✅ Code inserted successfully!",
      },
      ERRORS: {
        CSV_NOT_FOUND: "CSV log file not found",
        FILE_EMPTY: "File is empty",
        NO_FRONTMATTER: "No frontmatter found",
        NO_TAGS: "No tags found",
      },
      STATUS: {
        INSUFFICIENT_DATA: "Insufficient data",
      },
    },
    FORMS: {
      LABELS: {
        EXERCISE_NAME: "Exercise name",
        WORKOUT_NAME: "Workout name:",
      },
      PLACEHOLDERS: {
        ENTER_EXERCISE_NAME: "Enter exercise name",
        ENTER_CSV_PATH: "Enter CSV file path",
        ENTER_FOLDER_PATH: "Enter folder path",
      },
    },
    CHARTS: {
      LABELS: {
        REPS: "Reps",
        DATE: "Date",
        TREND_LINE: "Trend line",
      },
      TYPES: {
        VOLUME: "volume",
        WEIGHT: "weight",
        REPS: "reps",
      },
    },
    MUSCLES: {
      NAMES: {
        TRAP: "Trap",
        TRAP_MID: "TrapMid",
        LATS: "Lats",
        LOWER: "Lower",
        BICIPITI: "Bicipiti",
        TRICIPITI: "Tricipiti",
        AVAMBRACCI: "Avambracci",
        SCHIENA: "Schiena",
        PETTO: "Petto",
        ADDOMINALI: "Addominali",
        OBLIQUI: "Obliqui",
        QUADRICIPITI: "Quadricipiti",
        FEMORALI: "Femorali",
        GLUTEI: "Glutei",
        POLPACCI: "Polpacci",
        SPALLE_ANTERIORI: "Spalle Anteriori",
        SPALLE_LATERALI: "Spalle Laterali",
        SPALLE_POSTERIORI: "Spalle Posteriori",
      },
      POSITIONS: {
        ALTO: "Alto",
        MEDIO: "Medio",
        BASSO: "Basso",
      },
      GROUPS: {
        CORE: "Core",
      },
      BODY_PARTS: {
        UPPER_BODY: "Upper body",
      },
      TAGS: [
        // Main muscle groups - Chest
        "chest",
        "petto",
        "pettorale",
        "pettoralesuperior",
        "pettoraleinferior",
        "pettoralemedio",

        // Main muscle groups - Back
        "back",
        "schiena",
        "dorsale",

        // Main muscle groups - Shoulders
        "shoulders",
        "spalle",
        "deltoidi",
        "deltoideanteriore",
        "deltoidilaterale",

        // Main muscle groups - Arms
        "biceps",
        "bicipiti",
        "triceps",
        "tricipiti",

        // Main muscle groups - Legs
        "legs",
        "gambe",
        "quads",
        "quadricipiti",
        "hamstrings",
        "ischiocrurali",
        "femorali",

        // Main muscle groups - Glutes
        "glutes",
        "glutei",
        "gluteo",
        "grandegluteo",
        "abduttori",
        "adduttori",

        // Main muscle groups - Calves
        "calves",
        "polpacci",

        // Main muscle groups - Core
        "abs",
        "addominali",
        "core",
        "cardio",

        // Secondary muscle groups
        "forearms",
        "avambracci",
        "traps",
        "trapezi",
        "rear_delts",
        "deltoidi_posteriori",
        "deltoidiposteriori",

        // Exercise types that help determine muscle groups
        "push",
        "pull",
        "squat",
        "deadlift",
        "press",
        "curl",
        "extension",
        "fly",
        "row",
        "spintaanca",
      ],
      TAG_MAP: {
        // Main muscle groups - Chest
        chest: "chest",
        petto: "chest",
        pettorale: "chest",
        pettoralesuperior: "chest",
        pettoraleinferior: "chest",
        pettoralemedio: "chest",

        // Main muscle groups - Back
        back: "back",
        schiena: "back",
        dorsale: "back",

        // Main muscle groups - Shoulders
        shoulders: "shoulders",
        spalle: "shoulders",
        deltoidi: "shoulders",
        deltoideanteriore: "shoulders",
        deltoidilaterale: "shoulders",

        // Main muscle groups - Arms
        biceps: "biceps",
        bicipiti: "biceps",
        triceps: "triceps",
        tricipiti: "triceps",

        // Main muscle groups - Legs
        legs: "quads",
        gambe: "quads",
        quads: "quads",
        quadricipiti: "quads",
        hamstrings: "hamstrings",
        ischiocrurali: "hamstrings",
        femorali: "hamstrings",

        // Main muscle groups - Glutes
        glutes: "glutes",
        glutei: "glutes",
        gluteo: "glutes",
        grandegluteo: "glutes",
        abduttori: "glutes",
        adduttori: "glutes",

        // Main muscle groups - Calves
        calves: "calves",
        polpacci: "calves",

        // Main muscle groups - Core
        abs: "abs",
        addominali: "abs",
        core: "core",
        cardio: "core",

        // Secondary muscle groups
        forearms: "forearms",
        avambracci: "forearms",
        traps: "traps",
        trapezi: "traps",
        rear_delts: "rear_delts",
        deltoidi_posteriori: "rear_delts",
        deltoidiposteriori: "rear_delts",

        // Exercise types that help determine muscle groups
        push: "chest",
        pull: "back",
        squat: "quads",
        deadlift: "back",
        press: "shoulders",
        curl: "biceps",
        extension: "triceps",
        fly: "chest",
        row: "back",
        spintaanca: "glutes",
      } as Record<string, string>,
      KEYWORDS: [
        // Main muscle groups
        "chest",
        "petto",
        "pettorale",
        "back",
        "schiena",
        "dorsale",
        "shoulders",
        "spalle",
        "deltoidi",
        "biceps",
        "bicipiti",
        "triceps",
        "tricipiti",
        "legs",
        "gambe",
        "quads",
        "quadricipiti",
        "hamstrings",
        "ischiocrurali",
        "femorali",
        "glutes",
        "glutei",
        "gluteo",
        "abduttori",
        "adduttori",
        "calves",
        "polpacci",
        "abs",
        "addominali",
        "core",
        "forearms",
        "avambracci",
        "traps",
        "trapezi",
      ],
    },
    STATS: {
      LABELS: {
        SESSIONS: "Sessions: ",
        RECENT_TREND: "Recent trend: ",
        AVG_VOLUME: "Average volume: ",
      },
    },
    TRENDS: {
      STATUS: {
        STABLE: "Stable",
        INVARIANT: "Invariant",
        INCREASING: "Increasing",
        DECREASING: "Decreasing",
        STABLE_LOWER: "Stable (lower)",
        STABLE_HIGHER: "Stable (higher)",
      },
      DIRECTIONS: {
        UP: "up",
        DOWN: "down",
        NEUTRAL: "neutral",
      },
    },
    TIME_PERIODS: {
      WEEK: "Week",
      MONTH: "Month",
      YEAR: "Year",
    },
    COMMON: {
      UNITS: {
        WEIGHT_KG: "Weight (kg)",
      },
      TYPES: {
        EXERCISE: "exercise",
        WORKOUT: "workout",
      },
      DEFAULTS: {
        UNKNOWN: "Unknown",
        EXERCISE_NAME: "exercise",
        WORKOUT_NAME: "Workout",
      },
      NOT_AVAILABLE: "N/A",
    },
    TIMER: {
      TYPES: {
        COUNTDOWN: "Countdown",
        INTERVAL: "Interval",
      },
    },
    COMMANDS: {
      CREATE_CSV: "Create CSV log file",
      INSERT_TABLE: "Insert workout table",
      AUDIT_EXERCISE_NAMES: "Audit exercise names",
      ADD_EXERCISE_BLOCK: "Add exercise block",
      QUICK_LOG: "Quick log",
      EXPORT_WORKOUT_TO_CANVAS: "Export workout to canvas",
    },
    DESCRIPTIONS: {
      INSERT_TABLE:
        "This will insert a comprehensive workout dashboard with statistics, charts, and quick actions.",
    },
    SETTINGS: {
      LABELS: {
        CSV_PATH: "CSV log file path",
        EXERCISE_FOLDER: "Exercise folder path",
        DEFAULT_EXACT_MATCH: "Default exact match",
        TIMER_PRESETS: "Timer presets",
        DEFAULT_TIMER_PRESET: "Default timer preset",
        PRESET_NAME: "Preset name",
        PRESET_TYPE: "Timer type",
        PRESET_DURATION: "Duration (seconds)",
        PRESET_INTERVAL: "Interval time (seconds)",
        PRESET_ROUNDS: "Rounds",
        PRESET_SHOW_CONTROLS: "Show controls",
        PRESET_AUTO_START: "Auto start",
        PRESET_SOUND: "Sound",
        EXERCISE_BLOCK_TEMPLATE: "Exercise block template",
        WEIGHT_INCREMENT: "Weight increment (kg)",
        CUSTOM_PROTOCOLS: "Custom protocols",
        PROTOCOL_NAME: "Protocol name",
        PROTOCOL_ABBREVIATION: "Abbreviation",
        PROTOCOL_COLOR: "Badge color",
        SET_DURATION: "Default set duration (seconds)",
        SHOW_QUICK_LOG_RIBBON: "Show quick log ribbon icon",
        QUICK_WEIGHT_INCREMENT: "Quick weight increment (kg)",
      },
      DESCRIPTIONS: {
        CSV_PATH: "Path to the CSV file containing all workout log data",
        EXERCISE_FOLDER: "Path to the folder containing exercise pages",
        CREATE_CSV: "Create a new CSV log file with sample data",
        DEFAULT_EXACT_MATCH: "When enabled, exercise filtering uses exact name matching by default. Disable for fuzzy matching.",
        TIMER_PRESETS: "Create and manage reusable timer presets",
        DEFAULT_TIMER_PRESET: "Select a default preset for new timers",
        NO_PRESETS: "No timer presets configured. Click 'Add preset' to create one.",
        EXERCISE_BLOCK_TEMPLATE: "Template for exercise blocks. Available placeholders: {{exercise}}, {{duration}}, {{workout}}, {{preset}}",
        WEIGHT_INCREMENT: "Default weight increment for progressive overload (e.g., 2.5 for 2.5kg increments)",
        CUSTOM_PROTOCOLS: "Create custom workout protocols to track specialized training techniques",
        NO_CUSTOM_PROTOCOLS: "No custom protocols configured. Click 'Add protocol' to create one.",
        PROTOCOL_ABBREVIATION: "Short abbreviation shown in badge (max 3 characters)",
        PROTOCOL_COLOR: "Badge background color (hex format, e.g., #FF5733)",
        SET_DURATION: "Default time per set used in workout duration estimation (typical range: 30-60 seconds)",
        SHOW_QUICK_LOG_RIBBON: "Show a dumbbell icon in the left ribbon for quick logging on mobile and desktop",
        QUICK_WEIGHT_INCREMENT: "Weight increment for quick adjustment buttons in quick log modal (e.g., 2.5 for +2.5 / -2.5)",
      },
      SECTIONS: {
        CSV_MANAGEMENT: "CSV file management",
        FILTERING: "Filtering",
        TIMER_PRESETS: "Timer presets",
        TEMPLATES: "Templates",
        PROGRESSIVE_OVERLOAD: "Progressive overload",
        CUSTOM_PROTOCOLS: "Custom protocols",
        DURATION_ESTIMATION: "Duration estimation",
        QUICK_LOG: "Quick log",
      },
      BUTTONS: {
        ADD_PRESET: "Add preset",
        DELETE_PRESET: "Delete",
        SAVE_PRESET: "Save",
        CANCEL: "Cancel",
        ADD_PROTOCOL: "Add protocol",
        SAVE_PROTOCOL: "Save",
      },
      OPTIONS: {
        NONE: "None",
      },
      MESSAGES: {
        PRESET_NAME_REQUIRED: "Preset name is required",
        PRESET_NAME_EXISTS: "A preset with this name already exists",
        PRESET_DELETED: "Preset deleted",
        PRESET_SAVED: "Preset saved",
        CONFIRM_DELETE_PRESET: "Are you sure you want to delete this preset?",
        PROTOCOL_NAME_REQUIRED: "Protocol name is required",
        PROTOCOL_ABBREVIATION_REQUIRED: "Abbreviation is required (max 3 characters)",
        PROTOCOL_COLOR_REQUIRED: "Badge color is required",
        PROTOCOL_NAME_EXISTS: "A protocol with this name already exists",
        PROTOCOL_DELETED: "Protocol deleted",
        PROTOCOL_SAVED: "Protocol saved",
        CONFIRM_DELETE_PROTOCOL: "Are you sure you want to delete this protocol?",
      },
    },
    ERRORS: {
      TYPES: {
        VALIDATION: "Validation error",
        TABLE: "Table error",
        GENERIC: "Error",
      },
    },
    ICONS: {
      COMMON: {
        PERCENTAGE: "%",
        PLUS: "+",
        MINUS: "-",
        ARROW_UP: "⬆️",
        ARROW_DOWN: "⬇️",
        ARROW_NEUTRAL: "↔️",
        EMPTY: "",
      },
      TABLE: {
        REPS: "🔁 ",
        WEIGHT: "🏋️ ",
        VOLUME: "📊 ",
      },
      ACTIONS: {
        ADD: "➕",
        EDIT: "✏️",
        DELETE: "🗑️",
        REFRESH: "🔄",
      },
      STATUS: {
        SUCCESS: "✅",
        ERROR: "❌",
        WARNING: "⚠️",
        INFO: "ℹ️",
      },
      DASHBOARD: {
        QUICK_STATS: {
          PERIODS: {
            WEEK: "🗓️",
            MONTH: "📆",
            YEAR: "📈",
          },
          METRICS: {
            WORKOUTS: "🏋️",
            TOTAL_VOLUME: "📦",
            AVG_VOLUME: "📊",
          },
        },
        SUMMARY: {
          TOTAL_WORKOUTS: "🏋️",
          CURRENT_STREAK: "🔥",
          TOTAL_VOLUME: "📦",
          PERSONAL_RECORDS: "🏅",
        },
      },
      EXERCISE: {
        DEADLIFT: "💀",
        CURL: "💪",
        EXTENSION: "📏",
        BICEPS: "💪",
        TRICEPS: "💪",
        CORE: "🎯",
        FOREARM: "✊",
        BACK: "🦾",
        FLY: "🦅",
        HIP_TRUST: "🍑",
        SHOULDERS: "🦵",
        ARMS: "🦵",
        LEGS: "🦵",
        GLUTES: "🍑",
        CALVES: "🦵",
        TRAPS: "🔺",
        CARDIO: "⭐",
        PUSH: "🔼",
        PULL: "⬇️",
      },
    },
    LABELS: {
      GENERAL: {
        TOTAL_VOLUME: "Total volume (kg)",
        AVG_VOLUME: "Average volume (kg)",
        TOTAL_WEIGHT: "Total weight (kg)",
        AVG_WEIGHT: "Average weight (kg)",
        TOTAL_REPS: "Total reps",
        AVG_REPS: "Average reps",
        WORKOUTS: "Workouts",
        SEARCH: "Search",
      },
      TABLE: {
        DATE: "Date",
        EXERCISE: "Exercise",
        REPS: "Reps",
        REPETITIONS: "Repetitions",
        WEIGHT_WITH_UNIT: "Weight (kg)",
        VOLUME: "Volume",
        WEIGHT: "Weight",
        VOLUME_WITH_UNIT: "Volume (kg)",
        NOTES: "Notes",
        ACTIONS: "Actions",
        NO_DATA: "No data available",
        INVALID_DATE: "Invalid date",
        NOT_AVAILABLE: "N/A",
        TREND_LINE: "Trend line",
        ADD_LOG_BUTTON: "Add log",
        UP: "up",
        DOWN: "down",
        NEUTRAL: "neutral",
        TARGET_PREFIX: "Target:",
      },
      ACTIONS: {
        ADD: "Add",
        ADD_LOG: "Add log",
        EDIT: "Edit",
        EDIT_LOG_ENTRY: "Edit log entry",
        DELETE: "Delete",
        DELETE_LOG_ENTRY: "Delete log entry",
        DELETE_CONFIRM: "Are you sure you want to delete this log entry?",
        DELETE_SUCCESS: "Log entry deleted successfully!",
        DELETE_ERROR: "Error deleting log entry: ",
        REFRESH_SUCCESS: "Table refreshed successfully",
      },
      LOGS: {
        NO_DATA_TITLE: (exerciseName?: string) =>
          `No workout logs found for ${exerciseName && exerciseName.trim().length > 0 ? exerciseName : "exercise"}`,
        CREATE_FIRST_LOG_BUTTON_TEXT: (exerciseName?: string) =>
          `Create first workout log for ${exerciseName && exerciseName.trim().length > 0 ? exerciseName : "exercise"}`,
        CREATE_FIRST_LOG_BUTTON_ARIA: (exerciseName?: string) =>
          `Create first workout log for ${exerciseName && exerciseName.trim().length > 0 ? exerciseName : "exercise"}`,
        ADD_LOG_BUTTON_TEXT: (exerciseName?: string) =>
          `Add log for ${exerciseName && exerciseName.trim().length > 0 ? exerciseName : "Workout"}`,
        ADD_LOG_BUTTON_ARIA: (exerciseName?: string) =>
          `Add workout log for ${exerciseName && exerciseName.trim().length > 0 ? exerciseName : "Workout"}`,
        CREATE_LOG_BUTTON_TEXT: (exerciseName: string) =>
          `Create log for: ${exerciseName}`,
        CREATE_LOG_BUTTON_ARIA: (exerciseName: string) =>
          `Create workout log for ${exerciseName}`,
        NO_MATCH_MESSAGE: "No matching exercise data found",
      },
      DASHBOARD: {
        QUICK_ACTIONS: {
          TITLE: "Quick actions",
          ADD_WORKOUT_LOG: "Add workout log",
          VIEW_EXERCISES: "View exercises",
        },
        QUICK_STATS: {
          TITLE: "Quick stats",
          PERIODS: {
            WEEK: "This week",
            MONTH: "This month",
            YEAR: "This year",
          },
          METRICS: {
            WORKOUTS: "Workouts",
            TOTAL_VOLUME: "Total volume (kg)",
            AVG_VOLUME: "Avg volume (kg)",
          },
        },
        RECENT_WORKOUTS: {
          TITLE: "Recent workouts",
          FALLBACK_NAME: "Workout",
          VOLUME_SUFFIX: "kg",
        },
        SUMMARY: {
          TITLE: "Summary",
          TOTAL_WORKOUTS: "Total workouts",
          CURRENT_STREAK: "Current streak",
          CURRENT_STREAK_SUFFIX: "weeks",
          TOTAL_VOLUME: "Total volume",
          TOTAL_VOLUME_SUFFIX: "kg",
          PERSONAL_RECORDS: "Personal records",
        },
        VOLUME_ANALYTICS: {
          TITLE: "Volume analytics",
          DATASET_LABEL: "Daily volume (kg)",
          CHART_TITLE: "Volume trend (last 30 days)",
          MUSCLE_BREAKDOWN_TITLE: "Top exercises by volume",
          VOLUME_SUFFIX: "kg",
        },
        PROTOCOL_DISTRIBUTION: {
          TITLE: "Protocol distribution",
          SUBTITLE: "Last 30 days",
          NO_DATA: "No protocol data available",
          SETS_LABEL: "sets",
          PERCENT_LABEL: "%",
          FILTER_ACTIVE: "Filtering by:",
          CLEAR_FILTER: "Clear filter",
          CLICK_TO_FILTER: "Click to filter",
        },
        PROTOCOL_EFFECTIVENESS: {
          TITLE: "Protocol effectiveness",
          NO_DATA: "Not enough data (minimum 5 entries per protocol)",
          DISCLAIMER: "Note: Correlation does not imply causation",
          COLUMN_PROTOCOL: "Protocol",
          COLUMN_ENTRIES: "Entries",
          COLUMN_VOLUME_CHANGE: "Avg volume change",
          COLUMN_PROGRESSION: "Progression rate",
        },
        DURATION_COMPARISON: {
          TITLE: "Actual vs estimated duration",
          SUBTITLE: "Last 5 workouts",
          NO_DATA: "Not enough workout data to compare durations",
          COLUMN_WORKOUT: "Workout",
          COLUMN_DATE: "Date",
          COLUMN_ESTIMATED: "Estimated",
          COLUMN_ACTUAL: "Actual",
          COLUMN_VARIANCE: "Variance",
          VARIANCE_TREND_TITLE: "Accuracy trend",
          VARIANCE_TREND_IMPROVING: "Estimates are getting more accurate",
          VARIANCE_TREND_DECLINING: "Estimates are getting less accurate",
          VARIANCE_TREND_STABLE: "Estimate accuracy is stable",
          MINUTES_SUFFIX: "m",
          OVER_ESTIMATED: "Over",
          UNDER_ESTIMATED: "Under",
        },
        MUSCLE_TAGS: {
          TITLE: "Available muscle tags",
          DESCRIPTION:
            "Click on any tag to copy it. Use these tags in exercise files for proper categorization and tracking.",
          TOTAL_COUNT: (count: number) => `Total: ${count} tags available`,
          TOOLTIP: (tag: string) => `Click to copy: ${tag}`,
        },
        FILE_ERRORS: {
          TITLE: "Exercise file errors",
          ALL_VALID: "All exercise files are valid",
          NO_TAGS: "No muscle tags found",
          TOO_MANY_TAGS: (count: number) => `Too many muscle tags (${count})`,
          READ_ERROR: (message: string) => `Error reading file: ${message}`,
        },
      },
      CHARTS: {
        UP: "up",
        DOWN: "down",
        NEUTRAL: "neutral",
        TREND_TITLE_PREFIX: "Trend Volume: ",
        OVERALL_VARIATION_PREFIX: "Overall variation: ",
        VARIATION_FROM_TO: (startKg: string, endKg: string) =>
          ` (da ${startKg} kg a ${endKg} kg)`,
        VARIATION_SINGLE_VALUE: (value: string) => ` (Volume: ${value} kg)`,
        VARIATION_VALUE_LABEL: (value: string) => `Volume: ${value} kg`,
        SIGNIFICANT_INCREASE: "Aumento signif.",
        FALLBACK_TABLE_MESSAGE:
          "fallback table (charts plugin not available or error)",
      },
    },
    MODAL: {
      TITLES: {
        CREATE_LOG: "Create workout log",
        EDIT_LOG: "Edit workout log",
        INSERT_CHART: "Insert workout chart",
        INSERT_TABLE: "Insert workout log table",
        INSERT_TIMER: "Insert workout timer",
        INSERT_DASHBOARD: "Insert workout dashboard",
        CREATE_EXERCISE_PAGE: "Create exercise page",
        CREATE_EXERCISE_SECTION: "Create exercise section",
        CONFIRM_ACTION: "Confirm action",
        AUDIT_EXERCISE_NAMES: "Audit exercise names",
        ADD_EXERCISE_BLOCK: "Add exercise block",
        QUICK_LOG: "Quick log",
        CANVAS_EXPORT: "Export workout to canvas",
      },
      BUTTONS: {
        CREATE: "Create log",
        UPDATE: "Update log",
        INSERT_CHART: "Insert chart",
        RENAME_IN_CSV: "Rename in CSV",
        RENAME_FILE: "Rename file",
        INSERT_TABLE: "Insert table",
        INSERT_TIMER: "Insert timer",
        INSERT_DASHBOARD: "Insert dashboard",
        CANCEL: "Cancel",
        CONFIRM: "Confirm",
        CREATE_EXERCISE: "Create exercise page",
        CREATE_SECTION: "Create section",
        INSERT_EXERCISE_BLOCK: "Insert",
        UPDATE_TARGET_WEIGHT: "Update target",
        ADJUST_PLUS: "+",
        ADJUST_MINUS: "-",
        EXPORT: "Export",
      },
      NOTICES: {
        LOG_CREATED: "Workout log created successfully!",
        LOG_UPDATED: "Workout log updated successfully!",
        LOG_CREATE_ERROR: "Error creating log: ",
        LOG_UPDATE_ERROR: "Error updating log: ",
        CHART_INSERTED: "✅ Chart inserted successfully!",
        TABLE_INSERTED: "✅ Table inserted successfully!",
        TIMER_INSERTED: "✅ Timer inserted successfully!",
        DASHBOARD_INSERTED: "✅ Dashboard inserted successfully!",
        VALIDATION_FILL_ALL: "Please fill in all fields with valid values",
        VALIDATION_POSITIVE_VALUES:
          "Please enter valid positive values for reps and weight",
        VALIDATION_COMBINED_MODE:
          "⚠️ for 'exercise + workout' type you must fill both fields!",
        NO_ACTIVE_EDITOR: "No active markdown editor",
        INSERT_CODE_NO_FILE: "Open a markdown file to insert the code",
        EXERCISE_PAGE_CREATED: "Exercise page created successfully!",
        EXERCISE_PAGE_ERROR: "Error creating exercise page: ",
        EXERCISE_PAGE_NAME_REQUIRED: "Please enter an exercise name",
        EXERCISE_NAME_REQUIRED: "❌ please enter an exercise name",
        EXERCISE_SECTION_CREATED: "✅ exercise section created successfully!",
        DASHBOARD_CREATED: "Dashboard section created successfully",
        GENERIC_ERROR: "Error: ",
        TIMER_ELEMENTS_NOT_INITIALIZED: "Timer elements not initialized",
        AUDIT_NO_MISMATCHES: "✅ No mismatches found. All exercise files match CSV entries.",
        AUDIT_SCANNING: "Scanning exercise files...",
        AUDIT_RENAME_SUCCESS: "Successfully renamed exercise in CSV",
        AUDIT_RENAME_ERROR: "Error renaming exercise: ",
        AUDIT_CONFIRM_RENAME: "Are you sure you want to rename this exercise in the CSV?",
        AUDIT_RENAME_FILE_SUCCESS: "Successfully renamed exercise file",
        AUDIT_RENAME_FILE_ERROR: "Error renaming file: ",
        AUDIT_CONFIRM_RENAME_FILE: "Are you sure you want to rename this file?",
        EXERCISE_BLOCK_INSERTED: "✅ Exercise block inserted successfully!",
        CANVAS_EXPORTED: "Canvas exported successfully!",
        CANVAS_EXPORT_ERROR: "Error exporting to canvas: ",
        CANVAS_NO_EXERCISES: "No exercises found in workout file",
        TARGET_ACHIEVED: "Target Reached! Consider increasing weight",
        TARGET_DISMISSED: "Achievement badge dismissed",
        SUGGESTED_NEXT_WEIGHT: "Suggested next:",
        CONFIRM_UPDATE_TARGET: "Update target weight to",
      },
      LABELS: {
        EXERCISE: "Exercise:",
        REPS: "Reps:",
        WEIGHT: "Weight (kg):",
        NOTES: "Notes (optional):",
        WORKOUT: "Workout (optional):",
        WORKOUT_NAME: "Workout name:",
        WORKOUT_NAME_OPTIONAL: "Workout name (optional):",
        CHART_TYPE: "Chart type:",
        DATA_TYPE: "Data type:",
        TABLE_TYPE: "Table type:",
        DAYS_RANGE: "Days range:",
        DATA_LIMIT: "Data limit:",
        MAX_LOG_COUNT: "Maximum log count:",
        TABLE_COLUMNS: "Table columns:",
        BUTTON_TEXT: "Button text:",
        CUSTOM_TITLE: "Custom title:",
        TIMER_TYPE: "Timer type:",
        DURATION: "Duration (seconds):",
        INTERVAL_TIME: "Interval time (seconds):",
        ROUNDS: "Rounds:",
        TITLE: "Title:",
        EXERCISE_NAME: "Exercise name:",
        EXERCISE_PATH: "Exercise path:",
        SETS: "Sets:",
        REST_TIME: "Rest time (seconds):",
        NOTE: "Note:",
        TAGS: "Tags (comma separated):",
        FOLDER_PATH: "Folder path (optional):",
        CONFIRM_ACTION: "Confirm action",
        FILE_NAME: "File name",
        CSV_EXERCISE: "CSV exercise",
        SIMILARITY: "Similarity",
        STATUS: "Status",
        TIMER_DURATION: "Timer duration (seconds):",
        TIMER_PRESET: "Timer preset:",
        WORKOUT_FILE: "Workout file:",
        DATE_RANGE: "Date range (days):",
        TARGET_WEIGHT: "Target weight (kg):",
        TARGET_REPS: "Target reps:",
        PROTOCOL: "Protocol:",
        RECENT_EXERCISES: "Recent:",
        CANVAS_LAYOUT: "Layout",
        CANVAS_OPTIONS: "Options",
        LAYOUT_TYPE: "Layout type:",
        LAYOUT_HORIZONTAL: "Horizontal flow",
        LAYOUT_VERTICAL: "Vertical flow",
        LAYOUT_GROUPED: "Grouped by muscle",
      },
      PLACEHOLDERS: {
        EXERCISE_AUTOCOMPLETE: "Start typing to see available exercises...",
        REPS: "e.g., 10",
        REPS_RANGE: "8-10",
        WEIGHT: "e.g., 10.5",
        NOTES: "e.g., Good form, felt strong",
        WORKOUT: "e.g. Workout A, Training B, or use checkbox below",
        CUSTOM_TITLE: "Leave empty for automatic title",
        TIMER_TITLE: "Workout Timer",
        EXERCISE_NAME: "e.g. Bench Press",
        EXERCISE_PATH: "e.g. Exercises/Upper Body",
        SETS: "4",
        REST_TIME: "90",
        NOTE: "Push hard here. This is your fundamental exercise.",
        TAGS: "e.g., spalle, deltoidi, laterali, isolamento, macchina",
        FOLDER_PATH: "e.g., Exercises or leave empty for root",
      },
      CHECKBOXES: {
        USE_CURRENT_WORKOUT: "Use current page as workout",
        USE_CURRENT_WORKOUT_FILE: "Use current workout (file name)",
        SHOW_TREND_LINE: "Show trend line",
        SHOW_TREND_HEADER: "Show trend header",
        SHOW_STATISTICS: "Show statistics",
        SHOW_ADD_BUTTON: "Show 'Add log' button",
        EXACT_MATCH: "Exact match",
        DEBUG_MODE: "Debug mode",
        SEARCH_BY_NAME: "Search by file name",
        SHOW_CONTROLS: "Show controls",
        AUTO_START: "Auto start",
        SOUND: "Sound",
        INCLUDE_TIMER: "Include timer",
        INCLUDE_CHART: "Include chart",
        INCLUDE_TABLE: "Include table",
        INCLUDE_LOG: "Include log",
        TIMER_AUTO_START: "Timer auto start",
        TIMER_SOUND: "Timer sound",
        USE_PRESET_ONLY: "Use preset only (minimal code)",
        INCLUDE_DURATIONS: "Include timer durations",
        INCLUDE_STATS: "Include last performance stats",
        CONNECT_SUPERSETS: "Connect superset exercises with edges",
      },
      EXERCISE_STATUS: {
        CREATE_PAGE: "📝 create exercise page",
        SELECTED: "✅ exercise selected",
        NOT_FOUND: "⚠️ no exercises found",
        FOUND: (count: number) => `📋 ${count} exercises found`,
      },
      SELECT_OPTIONS: {
        CHART_TYPE: [
          { text: "Complete workout", value: "workout" },
          { text: "Specific exercise", value: "exercise" },
        ],
        DATA_TYPE: [
          { text: "Volume (kg)", value: "volume" },
          { text: "Weight (kg)", value: "weight" },
          { text: "Reps", value: "reps" },
        ],
        TABLE_TYPE: [
          { text: "Exercise + workout", value: "combined" },
          { text: "Specific exercise", value: "exercise" },
          { text: "Complete workout", value: "workout" },
        ],
        TABLE_COLUMNS: [
          {
            text: "Standard (Date, exercise, reps, weight, volume)",
            value: "standard",
          },
          { text: "Minimal (Date, exercise, reps, weight)", value: "minimal" },
        ],
        TIMER_TYPE: [
          { text: "Countdown", value: "countdown" },
          { text: "Interval", value: "interval" },
        ],
        PROTOCOL: [
          { text: "Standard", value: "standard" },
          { text: "Drop set", value: "drop_set" },
          { text: "Myo-reps", value: "myo_reps" },
          { text: "Rest-pause", value: "rest_pause" },
          { text: "Superset", value: "superset" },
          { text: "21s", value: "twentyone" },
        ],
      },
      SECTIONS: {
        CHART_TYPE: "Chart type",
        TABLE_TYPE: "Table type",
        TARGET: "Target",
        CONFIGURATION: "Configuration",
        DISPLAY_OPTIONS: "Display options",
        ADVANCED_OPTIONS: "Advanced options",
        TIMER_CONFIGURATION: "Timer configuration",
        WORKOUT: "Workout",
        EXERCISE_CONFIGURATION: "Exercise configuration",
        OPTIONS: "Options",
        PRESET: "Preset",
        PROGRESSIVE_OVERLOAD: "Progressive overload",
      },
      CODE_BLOCKS: {
        CHART: "workout-chart",
        TABLE: "workout-log",
        TIMER: "workout-timer",
        DASHBOARD: "workout-dashboard",
        DURATION: "workout-duration",
      },
      DEFAULTS: {
        CHART_DATE_RANGE: 180,
        CHART_DATE_RANGE_MIN: 1,
        CHART_DATE_RANGE_MAX: 365,
        CHART_LIMIT: 100,
        CHART_LIMIT_MIN: 1,
        CHART_LIMIT_MAX: 1000,
        TABLE_LIMIT: 12,
        TABLE_LIMIT_MIN: 1,
        TABLE_LIMIT_MAX: 1000,
        TIMER_DURATION: 90,
        TIMER_DURATION_MIN: 1,
        TIMER_DURATION_MAX: 3600,
        TIMER_INTERVAL: 30,
        TIMER_INTERVAL_MIN: 1,
        TIMER_INTERVAL_MAX: 3600,
        TIMER_ROUNDS: 5,
        TIMER_ROUNDS_MIN: 1,
        TIMER_ROUNDS_MAX: 100,
      },
    },
    TABLE: {
      COLUMNS: {
        DATE: "Date",
        EXERCISE: "Exercise",
        REPS: "Reps",
        WEIGHT: "Weight",
        VOLUME: "Volume",
        NOTES: "Notes",
        PROTOCOL: "Protocol",
        ACTIONS: "Actions",
      },
      LABELS: {
        DATA: "Date",
        VOLUME: "Volume",
        WEIGHT: "Weight",
        REPETITIONS: "Repetitions",
        NO_DATA: "No data available",
        INVALID_DATE: "Invalid date",
        NOT_AVAILABLE: "N/A",
        TREND_LINE: "Trend Line",
      },
      LIMITS: {
        DEFAULT: 50,
        MIN: 1,
        MAX: 1000,
      },
      ICONS: {
        REPS: "🔁 ",
        WEIGHT: "🏋️ ",
        VOLUME: "📊 ",
        EDIT: "✏️",
        DELETE: "🗑️",
      },
      DEFAULT_VISIBLE_COLUMNS: ["Date", "Reps", "Weight", "Volume", "Notes"],
      MESSAGES: {
        DELETE_CONFIRM: "Are you sure you want to delete this log entry?",
        DELETE_SUCCESS: "Log entry deleted successfully!",
        DELETE_ERROR: "Error deleting log entry: ",
        REFRESH_SUCCESS: "Table refreshed successfully",
        EDIT_TITLE: "Edit log entry",
        DELETE_TITLE: "Delete log entry",
      },
      DATE_KEYS: {
        INVALID: "invalid-date",
      },
      DEFAULTS: {
        BUTTON_TEXT: "➕ Add Log",
        EXACT_MATCH: true,
      },
      VALIDATION_ERRORS: {
        LIMIT_RANGE: (min: number, max: number, received: string) =>
          `limit must be a number between ${min} and ${max}, received: "${received}"`,
        COLUMNS_INVALID_TYPE:
          "columns must be an array of strings or a JSON string",
        COLUMNS_NOT_STRINGS: "columns must be an array of strings",
        BUTTON_TEXT_NOT_STRING: "buttonText must be a string",
      },
    },
  },
} as const;
