export const UI_ICONS = {
  COMMON: {
    PERCENTAGE: "%",
    PLUS: "+",
    MINUS: "-",
    ARROW_UP: "⬆️",
    ARROW_DOWN: "⬇️",
    ARROW_NEUTRAL: "↔️",
    EMPTY: "",
  },
  TABLE: {
    REPS: "🔁 ",
    WEIGHT: "🏋️ ",
    VOLUME: "📊 ",
  },
  ACTIONS: {
    ADD: "➕",
    EDIT: "✏️",
    DELETE: "🗑️",
    REFRESH: "🔄",
  },
  STATUS: {
    SUCCESS: "✅",
    ERROR: "❌",
    WARNING: "⚠️",
    INFO: "ℹ️",
  },
  DASHBOARD: {
    QUICK_STATS: {
      PERIODS: {
        WEEK: "🗓️",
        MONTH: "📆",
        YEAR: "📈",
      },
      METRICS: {
        WORKOUTS: "🏋️",
        TOTAL_VOLUME: "📦",
        AVG_VOLUME: "📊",
      },
    },
    SUMMARY: {
      TOTAL_WORKOUTS: "🏋️",
      CURRENT_STREAK: "🔥",
      TOTAL_VOLUME: "📦",
      PERSONAL_RECORDS: "🏅",
    },
  },
  EXERCISE: {
    DEADLIFT: "💀",
    CURL: "💪",
    EXTENSION: "📏",
    BICEPS: "💪",
    TRICEPS: "💪",
    CORE: "🎯",
    FOREARM: "✊",
    BACK: "🦾",
    FLY: "🦅",
    HIP_TRUST: "🍑",
    SHOULDERS: "🦵",
    ARMS: "🦵",
    LEGS: "🦵",
    GLUTES: "🍑",
    CALVES: "🦵",
    TRAPS: "🔺",
    CARDIO: "⭐",
    PUSH: "🔼",
    PULL: "⬇️",

  },
} as const;
