import { UI_ICONS } from "@app/constants/IconConstants";
import { UI_LABELS } from "@app/constants/LabelConstants";

export const TABLE_COLUMNS = {
  DATE: UI_LABELS.TABLE.DATE,
  EXERCISE: UI_LABELS.TABLE.EXERCISE,
  REPS: UI_LABELS.TABLE.REPS,
  WEIGHT: UI_LABELS.TABLE.WEIGHT,
  VOLUME: UI_LABELS.TABLE.VOLUME,
  NOTES: UI_LABELS.TABLE.NOTES,
  ACTIONS: UI_LABELS.TABLE.ACTIONS,
} as const;

export const TABLE_LABELS = {
  DATA: UI_LABELS.TABLE.DATE,
  VOLUME: UI_LABELS.TABLE.VOLUME_WITH_UNIT,
  WEIGHT: UI_LABELS.TABLE.WEIGHT,
  REPETITIONS: UI_LABELS.TABLE.REPETITIONS,
  NO_DATA: UI_LABELS.TABLE.NO_DATA,
  INVALID_DATE: UI_LABELS.TABLE.INVALID_DATE,
  NOT_AVAILABLE: UI_LABELS.TABLE.NOT_AVAILABLE,
  TREND_LINE: UI_LABELS.TABLE.TREND_LINE,
} as const;

export const TABLE_LIMITS = {
  DEFAULT: 50,
  MIN: 1,
  MAX: 1000,
} as const;

export const TABLE_ICONS = {
  REPS: UI_ICONS.TABLE.REPS,
  WEIGHT: UI_ICONS.TABLE.WEIGHT,
  VOLUME: UI_ICONS.TABLE.VOLUME,
  EDIT: UI_ICONS.ACTIONS.EDIT,
  DELETE: UI_ICONS.ACTIONS.DELETE,
} as const;

export const DEFAULT_VISIBLE_COLUMNS = [
  TABLE_COLUMNS.DATE,
  TABLE_COLUMNS.REPS,
  TABLE_COLUMNS.WEIGHT,
  TABLE_COLUMNS.VOLUME,
  TABLE_COLUMNS.NOTES,
] as const;

export const TABLE_MESSAGES = {
  DELETE_CONFIRM: UI_LABELS.ACTIONS.DELETE_CONFIRM,
  DELETE_SUCCESS: UI_LABELS.ACTIONS.DELETE_SUCCESS,
  DELETE_ERROR: UI_LABELS.ACTIONS.DELETE_ERROR,
  REFRESH_SUCCESS: UI_LABELS.ACTIONS.REFRESH_SUCCESS,
  EDIT_TITLE: UI_LABELS.ACTIONS.EDIT_LOG_ENTRY,
  DELETE_TITLE: UI_LABELS.ACTIONS.DELETE_LOG_ENTRY,
} as const;

export const TABLE_DATE_KEYS = {
  INVALID: "invalid-date",
} as const;

export const TABLE_DEFAULTS = {
  BUTTON_TEXT: `${UI_ICONS.ACTIONS.ADD} ${UI_LABELS.TABLE.ADD_LOG_BUTTON}`,
} as const;

export const TABLE_VALIDATION_ERRORS = {
  LIMIT_RANGE: (min: number, max: number, received: string) =>
    `limit must be a number between ${min} and ${max}, received: "${received}"`,
  COLUMNS_INVALID_TYPE:
    "columns must be an array of strings or a JSON string",
  COLUMNS_NOT_STRINGS: "columns must be an array of strings",
  BUTTON_TEXT_NOT_STRING: "buttonText must be a string",
} as const;
