import { App, normalizePath, Notice, TFile, TFolder } from "obsidian";
import type WorkoutChartsPlugin from "main";

/**
 * Service for generating and reading template files.
 * Templates are stored in a user-accessible folder in the vault (e.g., "Workout Templates").
 * Users can customize these templates to match their language and preferences.
 */
export class TemplateGeneratorService {
  private readonly defaultTemplateFolder = "Workout Templates";

  constructor(
    private app: App,
    private plugin: WorkoutChartsPlugin,
  ) {}

  /**
   * Get the template folder path.
   * Can be customized via settings in the future.
   */
  private getTemplateFolderPath(): string {
    return normalizePath(this.defaultTemplateFolder);
  }

  /**
   * Generate all default template files in English.
   * This creates files that users can then customize.
   */
  public async generateDefaultTemplates(
    overwrite: boolean = false,
  ): Promise<void> {
    try {
      const templateFolder = this.getTemplateFolderPath();

      // Create templates folder if it doesn't exist
      await this.ensureFolderExists(templateFolder);

      // Generate exercise page template
      await this.generateExercisePageTemplate(templateFolder, overwrite);

      // Generate tag reference document
      await this.generateTagReference(templateFolder, overwrite);

      new Notice(
        `Templates generated successfully in '${this.defaultTemplateFolder}'! You can now customize them.`,
      );
    } catch (error) {
      console.error("Failed to generate templates:", error);
      new Notice("Failed to generate templates. Check console for details.");
    }
  }

  /**
   * Read the exercise page template.
   * Returns default template if file doesn't exist.
   */
  public async getExercisePageTemplate(): Promise<string> {
    const templateFolder = this.getTemplateFolderPath();
    const templatePath = normalizePath(`${templateFolder}/exercise-page.md`);
    const file = this.app.vault.getAbstractFileByPath(templatePath);

    if (file instanceof TFile) {
      return await this.app.vault.read(file);
    }

    // Return default template if file doesn't exist
    return this.getDefaultExercisePageTemplate();
  }

  /**
   * Generate tag reference document listing all muscle tags.
   * Uses the same format as the "generate-tag-reference" command.
   */
  public async generateTagReference(
    folderPath: string,
    overwrite: boolean = false,
  ): Promise<void> {
    const tags = this.plugin.getMuscleTagService().getTagMap();
    const sortedTags = Array.from(tags.entries()).sort((a, b) =>
      a[0].localeCompare(b[0]),
    );

    let content = `---\n`;
    content += "title: Muscle Tags Reference\n";
    content +=
      "WARNING: DO NOT EDIT MANUALLY. This file is auto-generated by the Workout Plugin.\n";
    content += `tags:\n`;
    for (const [tag] of sortedTags) {
      content += `  - ${tag}\n`;
    }
    content += "---\n\n";
    content += "# Muscle Tags Reference\n\n";
    content +=
      "This file lists all available muscle tags from your muscle-tags.csv file.\n\n";
    content +=
      "**Note**: This file is auto-generated. To add or modify tags, use command 'Manage Muscle Tags'.\n";

    await this.createOrUpdateFile(
      folderPath,
      "Muscle Tags Reference.md",
      content,
      overwrite,
    );
  }

  /**
   * Generate the exercise page template file.
   */
  private async generateExercisePageTemplate(
    folderPath: string,
    overwrite: boolean = false,
  ): Promise<void> {
    const content = this.getDefaultExercisePageTemplate();
    await this.createOrUpdateFile(
      folderPath,
      "exercise-page.md",
      content,
      overwrite,
    );
  }

  /**
   * Get the default exercise page template in English.
   * This template is a blank structure that users fill in manually.
   * Note: You can rename 'exercise_name' to 'nome_esercizio' or any field name.
   * The plugin supports both 'exercise_name' (English) and 'nome_esercizio' (Italian).
   */
  private getDefaultExercisePageTemplate(): string {
    return `---
exercise_name:
exercise_type:
tags:
---

# Description

Type:

# Execution Technique



# Safety Notes

-

# Performance Log

\`\`\`workout-log
exercise: name
\`\`\`

### Chart

\`\`\`workout-chart
exercise: name
\`\`\`
`;
  }

  /**
   * Helper to create or update a file with content.
   */
  private async createOrUpdateFile(
    folderPath: string,
    fileName: string,
    content: string,
    overwrite: boolean,
  ): Promise<void> {
    const filePath = normalizePath(`${folderPath}/${fileName}`);
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);

    if (existingFile && !overwrite) {
      return;
    }

    if (existingFile instanceof TFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
  }

  /**
   * Ensure a folder exists, creating it if necessary.
   */
  private async ensureFolderExists(path: string): Promise<void> {
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!folder) {
      await this.app.vault.createFolder(path);
    } else if (!(folder instanceof TFolder)) {
      throw new Error(`Path '${path}' exists but is not a folder.`);
    }
  }
}
